### ISSUE TITLE
Nazwa sprzedawcy

### ISSUE THREAD

**Issue by fakk3** [Krukosz/Allegro_REST_RSS#1]
Czy udało by się dodać do skryptu możliwość wyświetlenia nazwy sprzedającego w wynikach? Z góry dziękuję.

**Comment by Krukosz** [comment]
Niestety allegro nie udostępnia tej informacji w nowym API. Jedyne co można zrobić to dodać nr sprzedającego w wynikach. https://github.com/allegro/allegro-api/issues/1416

**Comment by fakk3** [comment]
Jakbyś dodał wyświetlenie numeru sprzedawcy to byłbym wdzięczny, ponieważ umożliwia to blokowanie w czytniku rss niektórych sprzedawców i wyświetlanie ich aukcji.

**Comment by Krukosz** [comment]
Dodane [](https://github.com/Krukosz/Allegro_REST_RSS/commit/09d0faa3a17fa9fa3d8a8b193a14c27af2a49e67)

**Comment by Ostzie** [comment]
Jakiego czytnika używasz, który umożliwia blokowanie sprzedawców? Brakuje mi tej opcji w moim czytniku.

**Comment by Krukosz** [comment]
Nie używam takiej opcji - ale jeżeli Twój czytnik potrafi filtrować po jednym z tagów rss, to myślę, że dałoby radę dorobić takie coś.
Ja osobiście używam feedly.
