### ISSUE TITLE
Allegro Lokalnie

### ISSUE THREAD

**Issue by fakk3** [Krukosz/Allegro_REST_RSS#11]
Oferty z allegro lokalnie pojawiają się w czytniku RSS, ale po kliknięciu w przeglądarce otwiera się strona allegro z informacją, że przedmiot lub oferta nie istnieje.

**Comment by Aurosonic** [comment]
Potwierdzam, niestety link z numerem oferty nie przekierowuje do właściwego linku Allegro Lokalnie

**Comment by Krukosz** [comment]
@fakk3 @Aurosonic Proszę o udostępnienie parametrów wyszukiwania, żebym mógł odtworzyć bład.

**Comment by fakk3** [comment]
link do kanału http://localhost/allegro/index.php?categoryId=258477

link który otrzymuję po wejściu jest błędny i prowadzi do innych przedmiotów lub archiwum:

https://archiwum.allegro.pl/oferta/jerzy-pawlowski-najdluzszy-pojedynek-i1000042270.html (powinno być https://allegrolokalnie.pl/oferta/kid-dracula-or-unikat-or-ukv-or-bialy-kruk)

https://archiwum.allegro.pl/oferta/buty-sidi-streetburner-czarne-rozmiar-46-legnica-i1000042272.html

lub pojawiają linki z informacją, że oferta nie istnieje: 

https://allegro.pl/i1000068931.html (powinno pojawić się to https://allegrolokalnie.pl/oferta/ferrari-grand-prix-challenge-%E2%80%93-gameboy)

**Comment by Aurosonic** [comment]
Sytuacja dokładnie j.w. ;)

**Comment by Krukosz** [comment]
Ok, chyba znalazłem jak to rozdzielić - pole vendor o którym jest mowa [TUTAJ](https://github.com/allegro/allegro-api/issues/2267#issuecomment-546634819)
Postaram się wrzucić poprawkę jak znajdę czas na wdrożenie.

**Comment by Krukosz** [comment]
@fakk3 @Aurosonic Poprawione
[fix](https://github.com/Krukosz/Allegro_REST_RSS/commit/3077c6ffaa933dcfaa520a8040d11aa4b45f52de)

**Comment by fakk3** [comment]
Jak dodać fix? Po prostu wkleić kod do mastera?

**Comment by Krukosz** [comment]
Tak jak zawsze - plik index.php jest już zaktualizowany - trzeba w nim wrzucić swoje dane do klucza API i wrzucić na serwer

**Comment by Aurosonic** [comment]
Ok, dzięki, czy w tej sytuacji parametr "description" wyszukuje również na Allegro Lokalnie słowa kluczowe w opisach ofert  ?

**Comment by Krukosz** [comment]
Tak, ja zmieniłem to tylko na tyle, żeby te oferty które były wcześniej w listingu dały się otworzyć

**Comment by Krukosz** [comment]
Zamykam
