### ISSUE TITLE
bede testował

### ISSUE THREAD

**Issue by rydzyk184** [Krukosz/Allegro_REST_RSS#2]
Witam, zaczynam testowac aplikacje i o problemach bede informował.
Narazie doskwiera brak filtra CONDITION ( used, new)  - bardzo bym prosił o poprawkę.
zapytam jeszcze o cos przy okazji; rejestrujac aplikacjie na allegro developer apps co mam podac jako url do przekierowan ? adres gdzie znajduje sie skrypt z którego będe korzystał czy jak ?

pozdrawiam.

**Comment by Krukosz** [comment]
Nic takiego nie podajesz bo musisz wygenerowac inny typ klucza. Przy tworzeniu trzeba wybrac typ klucza "urzadzenie" (dla aplikacji konsolowych).

**Comment by Krukosz** [comment]
W dokumentacji jest informacja, że API zwraca info o stanie (nowy/używany), więc postaram się na dniach to dodać.

**Comment by rydzyk184** [comment]
dobrze, przydatne by tez było umieszczenie w wynikach wyszukiwania aktywnego linku pod zdjeciem który po kliknięciu przeniesie mnie na strone przedmiotu. dotychczas trzeba kliknąc w zdjecie w moim czytniku rss ale czasem zdjcia sie nie załąduja z powodu ich sporawego rozmiaru..... i nie ma jak przejść do adresu oferty.

**Comment by Ostzie** [comment]
Dołączam się do prośby o stan nowy/używany, mega przydatne.
Ale skoro już napisałeś, że dorobisz to trzymam kciuki!

**Comment by tcheslav** [comment]
Świetna robota, nowe / używane oczywiście bardzo przydatne.

**Comment by Krukosz** [comment]
Zrobione
[Commit](https://github.com/Krukosz/Allegro_REST_RSS/commit/cd47c786c2b7ee8b3ff9320ef840e1b781f878c7)

**Comment by Ostzie** [comment]
pięknie działa!
