### ISSUE TITLE
Ładowanie zdjęć

### ISSUE THREAD

**Issue by allerss** [Krukosz/Allegro_REST_RSS#3]
Przede wszystkim dziękuję za działającą wersję skryptu. Na razie testuję ją na dwóch agragatorach: RSSOwl oraz QuiteRSS. 

Pojawia się problem ze zdjęciami. Przy RSSOwl ładowane są zdjęcia w pełnej maksymalne rozdzielczości, przez co nie tylko czas ładowania jest bardzo wydłużony, ale i trudno się nawiguje. Przy QuiteRSS są miniaturki, ale i tak pobierane są ich wersje w pełnej rozdzielczości. Niby w kodzie skryptu jest ograncznik 100px, ale jak widać nie wszędzie on działa. Może lepiej podać adres do miniaturki tworzonej przez allegro i ew. ją pomniejszyć do 100px? Bo przy słabym łączu pobieranie ciężkich zdjęć jest bardzo frustrujące.

Z góry dziękuję za zajęcie się sprawą.

**Comment by allerss** [comment]
Dodam, że próbowałem podmienić kod związany ze zdjęciami ze starego skryptu alleRSS:

`if (count($offerObject[$i]->images) > 0) {
            $rss .=  "<a href=\"https://allegro.pl/i" . $offerObject[$i]->id . ".html\"><img src=\"" . $offerObject[$i]->images[0]->url . "\" style='float: left; max-height: 150px; max-width: 150px;'></a>\n";`

na

`if (isSet($object->photosInfo->item)) {
					foreach ($object->photosInfo->item as $key => $photo) {
						if ($photo->photoSize == "medium" && $photo->photoIsMain == 1) {
 		   					echo "<a href=\"https://allegro.pl/i" . $object->itemId . ".html\"><img src=\"" . $photo->photoUrl . "\"></a>\n";


Niestety, po tej operacji skrypt przestaje działać. Musi być jakiś sposób, aby pobierać miniaturki z allegro, które swoją drogą mają ograniczenie do 128px...

**Comment by Krukosz** [comment]
Zasób z którego pobierane sa oferty zwraca jedynie obrazki w pełnych rozmiarach. Jest to nawet zawarte w dokumentacji - max-height oraz max-width to sa moje ograniczenia tylko po stronie CSS aby nie rozjezdżało strony.

Druga sprawa: twój kod nie ma prawa działać, bo API zwraca mniej-więcej coś takiego: (regular/promoted)offers->item->images->url[i], a Twoje rozwiazanie najprawdopodobniej pochodzi z WebAPI

[Zdjecie](https://imgur.com/mVxm1K3)
[Dokumentacja](https://developer.allegro.pl/documentation/#operation/getListing)

I jeszcze potwierdzenie pytań o miniaturki:
[allegro-api-miniaturki](https://github.com/allegro/allegro-api/issues/1368)
[allegro-api-miniaturki2](https://github.com/allegro/allegro-api/issues/1355)

Miniaturkę da się jakoś pobrać - chociażby odpytujac stare API, ale w swoim projekcie wolałbym pozostać jedynie przy REST i wykorzystywać jego (często okrojone) zasoby - chociażby ze względu na szybkość działania

**Comment by allerss** [comment]
Dzięki za wiadomość. Rozumiem, że nie da się pobrać miniaturki z nowego API? Allegro nie przewidzidziało takiego czegoś?

**Comment by Krukosz** [comment]
Niestety - inna metoda to sale/offers, która posiada wszystkie informacje o aukcjach, ale jest to metoda niepubliczna i można nia wyswietlić tylko swoje oferty.
Na githubie allegro najczęściej przewijaja sie pytania o nazwe sprzedawcy oraz miniaturki i za każdym razem dostaje się odpowiedź o tym, że tej funkcjonalności nie ma nawet w planach.

**Comment by allerss** [comment]
Nie mogę pojąć, dlaczego allegro zrezygnowało ze wspierania RSS i trzeba pisać skrypty we własnym zakresie. Bardzo szkoda z tymi miniaturkami...

**Comment by kaem84** [comment]
prawdopodobnie przez obciążenie serwerów, a co za tym idzie koszty

**Comment by Krukosz** [comment]
Udało mi się zaimplementować w skrypcie obsługę miniaturek. Są one przeładowywane i tworzone w locie przez skrypt. Niestety nie ma tutaj żadnych opcji cache, ale wolne łącze nie powinno być już przeszkodą.

Oprócz aktualizacji index.php został dodany plik image.php oraz src/SimpleImage.php

**Comment by wiechec89** [comment]
Jako czytnika używam Mozilli Thunderbird i po tej zmianie miniaturki  w ogóle nie chcą się załadować. Wróciłem do starego rozwiązania.

**Comment by Krukosz** [comment]
Poprawiłem - akurat mój czytnik łykał takie rzeczy, więc nie zauważyłem.
Przetestowałem na innym - miniaturki się nie ładowały, a teraz już powinny działać.

Sprawdź proszę i daj znać

**Comment by wiechec89** [comment]
OK, sprawdzone - działa
Dzięki.

**Comment by kaem84** [comment]
Na RSSOwl obrazki nadal ładują się wielkie

**Comment by kaem84** [comment]
Na RSSOwl obrazki nadal są duże

**Comment by Krukosz** [comment]
Na pewno zaladowales index.php w nowej wersji?

**Comment by Krukosz** [comment]
Bo obrazki beda sie i tak ladowaly troche wolniej bo serwer musi je przetworzyc ale do uzytkownika koncowego wychodza jako miniaturki o dluzszym boku 128px

**Comment by kaem84** [comment]
Heh w ogóle teraz z nową wersją wcale mi skrypt nie działa

> Błąd przetwarzania XML: niezrozumiała seria znaków po elemencie dokumentu
> Obszar: http://www.***.pl/kaem/alleRSS.php?
> Numer wiersza: 2, kolumna 1:<b>Notice</b>:  Use of undefined constant clientID - assumed 'clientID' in <b>/home/kaem/alleRSS.php</b> on line <b>102</b><br />

edit:
naprawiłem usuwając ukośniki // przed "const clientID" i  "const clientSECRET"
edit2:
mam najnowszą wersję skryptu i wszystkie nowe pliki i dalej obrazki mam w większości bardzo duże na RRSOwl. Może nowe pliki mają mieć uprawnienia na zapis? A może stare wyszukania RRS pokazują duże obrazki a wszystkie nowe będą już miały małe?

**Comment by damianos56** [comment]
Wgrałem najnowszą wersję skryptu, ale nie wyświetlają mi się miniaturki wogóle ;/
Sprawdzałem na 3 czytnikach.

**Comment by Krukosz** [comment]
@kaem84 Możliwe, że stare wpisy ładuje Ci z cache. Zrób testowo sobie nowy kanał i sprawdź. Miniaturki to jest prosty skrypt generujący obrazki w php, nie uzywający w ogóle zapisu na dysk.
@damianos56 Sprawdź czy odkomentowałeś dwie linie z clientID, tak jak pisał kolega wyżej

**Comment by damianos56** [comment]
Linie są odkomentowane.
Wklejając link do przeglądarki jest wpis <img src=... , ale zdjęcia w czytnikach się nie otwierają.
W RSSOwl jest mały czarny kwadracik z x zamiast miniaturki.
Nie wiem w czym jest problem.

**Comment by Krukosz** [comment]
@damianos56 Podaj mi proszę jakich argumentów GET używasz (parametrów wyszukiwania)

**Comment by damianos56** [comment]
http://nazwa_domeny/rss/index.php?string=stolik
najprostszy do testów próbuje
Jeszcze próbowałem generować dwa typy kluczy REST API ( WEB , DEVICE).
Rozumiem,że ma być typ WEB?
Jaki adres przekierowań trzeba wpisać przy kluczu REST API typu WEB?

edit: Właśnie uruchomiłem dla testu skrypt na apachu w windowsie i miniaturki działają...
Skrypt mi nie działa na apachu w CentOS 7.Nie wiem co na linuksie mam nie tak.Błędów żadnych nie widzę.

**Comment by Krukosz** [comment]
@damianos56 Nie, generujesz jeden klucz typu Device. Dla RSS nie było sensu zastosowanie klucza web.
Spróbuj uruchomić skrypt w przeglądarce i sprawdź czy serwer nie zwraca błędów (np. brak biblioteki GD)

**Comment by damianos56** [comment]
> 
> 
> @damianos56 Nie, generujesz jeden klucz typu Device. Dla RSS nie było sensu zastosowanie klucza web.
> Spróbuj uruchomić skrypt w przeglądarce i sprawdź czy serwer nie zwraca błędów (np. brak biblioteki GD)

Trafiłeś w 10! Brakowało mi na linuksie biblioteki php-gd.
Miniaturki działają.
Dziękuje;) Biorę się za dalsze testowanie.
