### ISSUE TITLE
API response error

### ISSUE THREAD

**Issue by Ostzie** [Krukosz/Allegro_REST_RSS#4]
Niestety otrzymuję następujący błąd:
API response error
error: Unauthorized
error_description: Bad credentials

Wygenerowałem nowy klucz, typu device, korzystając z opcji:
"Aplikacja będzie działać w środowisku bez dostępu do przeglądarki albo klawiatury (np. aplikacja konsolowa albo na urządzeniu typu telewizor)
Aplikacja otrzyma OAuth grant-type: device_code"

Klucz Client ID / klucz WebAPI wpisałem w pliku token.json w miejsce pomiędzy "" zastępując dupa1, natomiast 
Klucz Client Secret wpisałem w pliku token.json w miejsce pomiędzy "" zastępując dupa2
Wygląda to tak:
{"attr1":"7ab******d8d","attr2":"wDy******5mc"}

Całość przesłałem na serwer
Odpytuje w następujący sposób:
http://www.*******.pl/index.php?string=warcraft

Gdzie popełniam błąd?

**Comment by Krukosz** [comment]
Plik token.json przechowuje wygenerowany token z odpowiedzią serwera. Nie trzeba go nawet wrzucać na serwer - skrypt go wygeneruje sam.

Swój klucz dodajesz w pliku index.php - muszę to uwzględnić w dokumentacji

**Comment by Ostzie** [comment]
Wszystko OK,
