### ISSUE TITLE
zmiana kolejnosci informacji w wynikach

### ISSUE THREAD

**Issue by rydzyk184** [Krukosz/Allegro_REST_RSS#6]
Jak zrobic aby zaraz pod tytułem oferty w pierwszej kolejnosci była CENA ? potem typ oferty i reszta informacji.  probowałem zmieniac w index.php kolejnosc tych formułek lecz bez rezultatu 
`$offerPrice =  "Cena: " . $offerSellingMode->price->amount . " " . $offerSellingMode->price->currency  . $printLineSeparator;
            $offerType = "Ogłoszenie" . $printLineSeparator;`

Przełądowanie zdjec na miniaturki działa dobrze lecz sa dla mnie zbyt małe bo max 128x128.
Próbowałem zmienic to w linice kodu `left; max-height: 384px; max-width: 384px;'></a>\n";
        }` lecz dalej ładuja sie w tym samym małym rozmiarze

**Comment by Krukosz** [comment]
W pliku `index.php` miniaturki masz tylko ostylowane. Sama wielkosc jest produkowana w pliku `image.php`.
Zmień liczbe na to co chcesz w linijce:
`imageResize($_GET['url'], 128);`
A co do zmiany kolejnosci - tam jest zmienna `$rss`, ktora pokolei zbiera tekst do wyswietlenia. Prześledź ją i ewentualnie pozmieniaj kolejność

**Comment by rydzyk184** [comment]
zrobione i działa, jest opcja aby wyświetlać czas dodania oferty/ogłoszenia zamiast parametru - ending time ?

**Comment by Krukosz** [comment]
Gdyby tak sie dalo to sam bym tego uzywal :)
Allegro nie udostepnia nigdzie publicznie parametru `startingTime`

**Comment by Krukosz** [comment]
Zamykam
