### ISSUE TITLE
Pytanie o miniaturki

### ISSUE THREAD

**Issue by allerss** [Krukosz/Allegro_REST_RSS#7]
Dziękuję za działającą wersję z miniaturkami. Działa wyśmienicie. Czy w kodzie można dowolnie zmieniać rozmiar miniaturki? Np. na 160px?

**Comment by Krukosz** [comment]
W poprzednim zgłoszeniu to omówiłem:
https://github.com/Krukosz/Allegro_REST_RSS/issues/6#issuecomment-485244512

**Comment by allerss** [comment]
Dziękuję, musiałem przeoczyć tę kwestię. Działa wspaniale.
